core/urls.py
from django.urls import path
from core import views
from crud.views import update_order_status

urlpatterns = [
    path ('', views.index, name='index'),
    path ('catalogo/', views.catalogo, name='catalogo'),
    path('catalogo/filter/', views.filter_products, name='filter_products'),
    path ('accesorios/', views.accesorios, name='accesorios'),
    path ('kits/', views.kits, name='kits'),
    path ('contacto/', views.contacto, name='contacto'),
    path ('producto/<id>', views.producto, name='producto'),
    path ('neworder/', views.new_order_wishlist, name='new-order-wishlist'),
    path ('neworder/<id>', views.new_order, name='new-order'),
    path('orders/<int:id>/', views.order_detail, name='myorder-detail'),
    path('orders/', views.order_list, name='my-orders'),
    path('editar-perfil/<id>', views.editar_perfil, name='editar-perfil'),
    path('about/', views.about, name='about'),
    path('order/update-status/<int:order_id>/<str:status>/', update_order_status, name='update-order-status')
]

crud/urls.py
from django.urls import path
from crud import views

urlpatterns = [
    path ('product-list/', views.product_list, name='product-list'),
    path ('add-product/', views.add_product, name='add-product'),
    path ('order-list/', views.order_list, name='order-list'),
    path('order/<int:id>/', views.order_detail, name='order-detail'),
    path('product-list/delete/<id>', views.productlist_delete, name='productlist-delete'),
    path('product-list/edit/<id>', views.productlist_edit, name='productlist-edit'),
    path('product-list/detail/<id>', views.product_detail, name='product-detail'),
]

servitelWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from core import views as core_views
from crud import views as crud_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('login.urls')),
    path('', include('core.urls')),
    path('crud/', include('crud.urls')),
] 

core/models.py
from django.db import models
from crud.models import Product
from login.models import User

class Order(models.Model):
    STATUS_CHOICES = [
        ('PC', 'Pendiente Confirmación'),
        ('CF', 'Confirmado'),
        ('EP', 'En preparación'),
        ('EN', 'Entregado'),
        ('CN', 'Cancelado'),
    ]

    user = models.ForeignKey(User, verbose_name='Cliente', on_delete=models.CASCADE)
    total = models.PositiveIntegerField(verbose_name='Total')
    status = models.CharField(verbose_name='Estado', max_length=2, choices=STATUS_CHOICES, default='PC')
    created_at = models.DateTimeField(verbose_name='Fecha registro',auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Fecha actualización',auto_now=True)
    fees = models.PositiveIntegerField(verbose_name='Cuotas', default=1)

    class Meta:
        verbose_name = 'pedido'
        verbose_name_plural = 'pedidos'

    def __str__(self):
        return f"{self.id}"

class OrderDetail(models.Model):
    order = models.ForeignKey(Order, verbose_name='Pedido', on_delete=models.CASCADE)
    product = models.ForeignKey(Product,verbose_name='Producto', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='Cantidad')
    unit_price = models.PositiveIntegerField(verbose_name='Precio unitario')
    subtotal = models.PositiveIntegerField(verbose_name='Subtotal')

    class Meta:
        verbose_name = 'detalle solicitud'
        verbose_name_plural = 'detalle solicitudes'

    def __str__(self):
        return f"{self.order}-{self.product}"

crud/models.py
from django.db import models
import re

# Create your models here.
class ProductManager(models.Manager):
    def validador_campos(self, postData):
        JUST_LETTERS_NUMBERS = re.compile(r'^[a-zA-Z0-9\sáéíóúÁÉÍÓÚñÑ]+$')
        
        errors = {}
        
        # Validar nombre del producto
        if len(postData['product'].strip()) < 2 or len(postData['product'].strip()) > 50:
            errors['product_len'] = "El nombre del producto debe tener entre 2 y 50 caracteres"
        
        if not JUST_LETTERS_NUMBERS.match(postData['product']):
            errors['just_letters_numbers'] = "El nombre del producto solo puede contener letras, números y espacios"

        # Validar descripción
        if postData.get('description') and len(postData['description'].strip()) > 500:
            errors['description_len'] = "La descripción no puede tener más de 500 caracteres"

        # Validar categoría
        if postData['category'] not in ['CA', 'KI', 'AC']:
            errors['category'] = "Categoría no válida"

        # Validar precio
        try:
            price = int(postData['price'])
            if price < 0:
                errors['price'] = "El precio no puede ser negativo"
        except ValueError:
            errors['price'] = "El precio debe ser un número entero"

        # Validar cámaras y canales si la categoría es 'Kits'
        if postData['category'] == 'KI':
            if 'cameras' not in postData or not postData['cameras'].isdigit() or int(postData['cameras']) <= 0:
                errors['cameras'] = "Debes ingresar un número de cámaras para la categoría 'Kits'"
            if 'channels' not in postData or not postData['channels'].isdigit() or int(postData['channels']) <= 0:
                errors['channels'] = "Debes ingresar un número de canales para la categoría 'Kits'"
        else:
            # Validar cámaras
            if postData.get('cameras'):
                try:
                    cameras = int(postData['cameras'])
                    if cameras < 0:
                        errors['cameras'] = "El número de cámaras no puede ser negativo"
                except ValueError:
                    errors['cameras'] = "El número de cámaras debe ser un número entero"

            # Validar canales
            if postData.get('channels'):
                try:
                    channels = int(postData['channels'])
                    if channels < 0:
                        errors['channels'] = "El número de canales no puede ser negativo"
                except ValueError:
                    errors['channels'] = "El número de canales debe ser un número entero"
        
        return errors
# Create your models here.
class Product(models.Model):
    CATEGORY_CHOICES = [
        ('CA', 'Cámaras'),
        ('KI', 'Kits'),
        ('AC', 'Accesorios'),
    ]

    product = models.CharField(verbose_name='Producto', max_length=50)
    description = models.TextField(verbose_name='Descripción',null=True,blank=True)
    category = models.CharField(verbose_name='Categoría', max_length=2, choices=CATEGORY_CHOICES, default='KI')
    price = models.PositiveIntegerField(verbose_name='Precio', blank=True, default=0)
    cameras = models.PositiveIntegerField(verbose_name='Cámaras', null=True, blank=True)
    channels = models.PositiveIntegerField(verbose_name='Canales', null=True, blank=True)
    image = models.ImageField(verbose_name='Imagen',upload_to='productos',null=True,blank=True)
    created_at = models.DateTimeField(verbose_name='Fecha registro',auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Fecha actualización',auto_now=True)
    objects = ProductManager()

    class Meta:
        verbose_name = 'producto'
        verbose_name_plural = 'productos'
        ordering = ['product']

    def __str__(self) -> str:
        return self.product


        

login/models.py
from django.db import models
import re
from django.utils import timezone
from datetime import datetime, timedelta
from django.contrib.auth.models import Group, Permission
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin


# Create your models here.
class UserManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('El email debe ser proporcionado')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        
        if 'is_staff' in extra_fields and extra_fields['is_staff']:
            if not password:
                raise ValueError('El personal de staff debe tener una contraseña')
            user.set_password(password)
        elif password:
            user.set_password(password)
        else:
            user.set_unusable_password()
        
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields['rol'] = 'ADMIN'

        if not password:
            raise ValueError('Los superusuarios deben tener una contraseña')
        name = extra_fields.get('name')
        last_name = extra_fields.get('last_name')

        while not name:
            name = input('El nombre debe ser proporcionado: ')
            if not name:
                print('El nombre es obligatorio.')
        
        while not last_name:
            last_name = input('El apellido debe ser proporcionado: ')
            if not last_name:
                print('El apellido es obligatorio.')

        extra_fields['name'] = name
        extra_fields['last_name'] = last_name


        

        return self.create_user(email, password, **extra_fields)

    def get_by_natural_key(self, email):
        return self.get(email=email)

    def validador_campos(self, postData, is_staff):
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        JUST_LETTERS = re.compile(r'^[a-zA-Z.]+$')
        PASSWORD_REGEX = re.compile(r'^(?=\w*\d)(?=\w*[A-Z])(?=\w*[a-z])\S{8,16}$')
        PHONE_REGEX = re.compile(r'^(\+\d{1,3}\d{9,15}|\+56\d{9})$')

        
        errors = {}

        email = postData.get('email', None)
        name = postData.get('name', '').strip()
        last_name = postData.get('last_name', '').strip()
        phone_number = postData.get('phone_number', '').strip()

        if not email:
            errors['email'] = "El email es obligatorio"
        elif not EMAIL_REGEX.match(email):
            errors['email_format'] = "Formato correo no válido"
        
        if not name or len(name) < 2 or len(name) > 30:
                errors['name_len'] = "Nombre debe tener entre 2 y 30 caracteres"
        if not last_name or len(last_name) < 2 or len(last_name) > 30:
            errors['last_name_len'] = "Apellido debe tener entre 2 y 30 caracteres"
        if not JUST_LETTERS.match(name) or not JUST_LETTERS.match(last_name):
            errors['just_letters'] = "Solo se permite el ingreso de letras en el nombre y apellido"
        
        if not is_staff:
            # Campos obligatorios para usuarios que no son staff
            
            comuna = postData.get('comuna', '').strip()
            birthday = postData.get('birthday', '').strip()
            gender = postData.get('gender', '').strip()

            
            if not phone_number or not PHONE_REGEX.match(phone_number):
                errors['phone_number'] = "Número de teléfono inválido"
            if not comuna:
                errors['comuna'] = "La comuna es obligatoria"
            if not birthday:
                errors['birthday'] = "La fecha de nacimiento es obligatoria"
            else:
                try:
                    birth_date = datetime.strptime(birthday, '%Y-%m-%d')
                    age = (datetime.now() - birth_date).days // 365
                    if age < 18:
                        errors['birth_date'] = "Debes ser mayor de 18 años"
                except ValueError:
                    errors['birth_date_format'] = "Formato de fecha de nacimiento no válido"
            if not gender:
                errors['gender'] = "El género es obligatorio"
        else:
            if phone_number:
                if not PHONE_REGEX.match(phone_number):
                    errors['phone_number'] = "Número de teléfono inválido"
            

        

        # Validación de contraseña (solo si está presente)
        password = postData.get('password', None)
        if password:
            if not PASSWORD_REGEX.match(password):
                errors['password_format'] = "Formato contraseña no válido"
            if postData['password'] != postData['password_confirm']:
                errors['password_confirm'] = "Contraseñas no coinciden"
            if len(postData['password']) < 8 or len(postData['password']) > 15:
                errors['password_len'] = "La cantidad de caracteres debe ser entre 8 y 15"


        birth_date = postData.get('birthday', None)  
        if birth_date:
            try:
                birth_date = datetime.strptime(birth_date, '%Y-%m-%d')  # Cambia el formato si es necesario
                age = (datetime.now() - birth_date).days // 365
                if age < 18:
                    errors['birth_date'] = "Debes ser mayor de 18 años."
            except ValueError:
                errors['birth_date_format'] = "Formato de fecha de nacimiento no válido."

        return errors

class Comuna(models.Model):
    comuna = models.CharField(verbose_name='COMUNA', max_length=100)

    def __str__(self):
        return self.comuna

def default_birthday():
    return datetime.now().date() - timedelta(days=365*18)

class User(AbstractBaseUser, PermissionsMixin):
    GENERO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('SE', 'Sin especificar'),
    ]

    name = models.CharField(verbose_name='NOMBRE', max_length=50, blank=True, null=True)
    last_name = models.CharField(verbose_name='APELLIDO', max_length=50, blank=True, null=True)
    birthday = models.DateField(verbose_name='FECHA DE NACIMIENTO', default=default_birthday, null=True)
    phone_number = models.CharField(verbose_name='TELÉFONO', max_length=15, blank=True, null=True)
    gender = models.CharField(verbose_name='GÉNERO', max_length=2, choices=GENERO_CHOICES, default='SE', null=True)
    comuna = models.ForeignKey(Comuna, on_delete=models.CASCADE, verbose_name='COMUNA', blank=True, null=True)
    email = models.EmailField(verbose_name='CORREO', max_length=100, unique=True, blank=True)
    password = models.CharField(verbose_name='CLAVE', max_length=250, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    rol = models.CharField(max_length=20, default='USER')
    created_at = models.DateTimeField(verbose_name='Fecha registro', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Fecha actualización', auto_now=True)
    verification_token = models.CharField(max_length=100, blank=True, null=True)
    last_login = models.DateTimeField(verbose_name='Último inicio de sesión', blank=True, null=True, default=timezone.now)
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "usuario"
        verbose_name_plural = "usuarios"
        
    def __str__(self):
        return f"{self.name} {self.last_name}"
    
    

    # Establece un nombre relacionado para evitar conflictos
    groups = models.ManyToManyField(Group, related_name='custom_user_set', blank=True)
    user_permissions = models.ManyToManyField(Permission, related_name='custom_user_permissions_set', blank=True)

crud/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class ProductForm(forms.ModelForm):
    description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'style': 'resize: none; height:80px'})
    )

    class Meta:
        model = Product
        fields = ['product', 'description', 'cameras', 'channels','price', 'image', 'category']
        widgets = {
            'product': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'cameras': forms.NumberInput(attrs={'class': 'form-control'}),
            'channels': forms.NumberInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
        }

crud/templates/crud/add-product.html
{% extends 'crud/base.html' %}

{% block title %}Agregar Producto{% endblock %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'crud/css/form-product.css' %}">
{% endblock %}

{% block first_content %}
<section id="form_sptn" class="container mycontainer mx-auto">
    {% if messages %}
    <div class="alert {{ request.session.level_mensaje }} alert-dismissible" role="alert">
        <ul>
            {% for message in messages %}
            <li><strong>{{message}}</strong></li>
            {% endfor %}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </ul>
    </div>
    {% endif %}

    <div id="container_new" class="container px-0 mx-0 mb-2 py-3">
        <h3 class="text-center">Formulario registro nuevos productos</h3>
    <div class="container myform my-2 pt-2 p-md-5">
        <form class="row g-3" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-md-12 form-group mb-3">
                <label for="product" class="fw-bold">Producto</label>
                <div class="input-group mt-2">
                    {{ form.product }}
                </div>
            </div>
            <div class="col-md-12 form-group mb-3">
                <label for="description" class="fw-bold">Descripción</label>
                <div class="input-group mt-2">
                    {{ form.description }}
                </div>
            </div>
            <div class="col-md-6 form-group mb-3">
                <label for="cameras" class="fw-bold">Cámaras</label>
                <div class="input-group mt-2">
                    {{ form.cameras }}
                </div>
            </div>
            <div class="col-md-6 form-group mb-3">
                <label for="channels" class="fw-bold">Canales</label>
                <div class="input-group mt-2">
                    {{ form.channels }}
                </div>
            </div>
            <div class="col-md-6 form-group mb-3">
                <label for="category" class="fw-bold">Categoría</label>
                <div class="input-group mt-2">
                    {{ form.category }}
                </div>
            </div>
            <div class="col-md-6 form-group mb-3">
                <label for="price" class="fw-bold">Precio</label>
                <div class="input-group mt-2">
                    {{ form.price }}
                </div>
            </div>
            <div class="col-md-12 form-group mb-3">
                <label for="image" class="fw-bold">Imagen</label>
                <div class="input-group mt-2">
                    {{ form.image }}
                </div>
                {% if form.instance.image %}
                <div class="row my-2">
                    <div class="col-12">
                        <img class="img-update mx-auto pt-4" src="{{ form.instance.image.url }}" alt="">
                    </div>
                </div>
                {% endif %}
            </div>
            <div class="container-fluid ">
                <div class="d-flex flex-row-reverse justify-content-center p-2">
                    <input type="submit" class="btn btn-primary mx-1 mx-md-2" id="registrar" value="Registrar">
                    <input type="reset" class="btn btn-reset mx-0 mx-md-2" id="restablecer" value="Restablecer">
                    <a class="btn btn-secondary mx-1 mx-md-2" href="{% url 'product-list' %}">Volver</a>
                </div>
            </div>
        </form>
    </div>
</section>
{% endblock %}

crud/templates/crud/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block meta_extra %}{% endblock %}
    <title>{% block title %}{% endblock %} | ServitelWeb </title>

    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    {% block extra_css %}{% endblock %}
    <link rel="stylesheet" href="{%static 'crud/css/navcrud.css' %}" />
    <link rel="icon" href="{% static 'crud/img/logo_icon.png' %}" type="image/x-icon">

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</head>


<body>

    <nav>
        {% include 'crud/navbar.html' %}
    </nav>

    {% block navbar_script %}
    {% endblock %}

    <main>
        {% block first_content %}{% endblock %}
        {% block second_content %}{% endblock %}


        {% block my_js %}{% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous"></script>
</body>

</html>

crud/templates/crud/order-detail.html
{% extends 'crud/base.html' %}
{% block title %}Detalle del Pedido{% endblock %}


{% load static %}
{% block meta_extra %}
    <meta name="csrf-token" content="{{ csrf_token }}">
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'crud/css/form-product.css' %}">
<link rel="stylesheet" href="{% static 'crud/css/detail.css' %}">
{% endblock %}

{% block first_content %}
<div class="container mycont">
    <div class="row">
        <div class="col-12">
            <div class="row">
                <!-- Columna 1: Detalles del Pedido -->
                <div class="col-md-6">
                    <h3>Detalle del Pedido #{{ order.id }}</h3>
                    <ul class="list-unstyled">
                        <li><strong>Cliente:</strong> {{ order.user }}</li>
                        <li class="flex-container">
                            <strong><label for="status">Estado:</label></strong>
                            <form method="post" action="{% url 'order-detail' order.id %}" id="status-form">
                                {% csrf_token %}
                                <select class="form-control" id="status" name="status">
                                    {% for key, value in order.STATUS_CHOICES %}
                                        <option value="{{ key }}" {% if order.status == key %}selected{% endif %}>{{ value }}</option>
                                    {% endfor %}
                                </select>
                            </form>
                        </li>
                        <li><strong>Fecha de creación:</strong> {{ order.created_at }}</li>
                        <li class="d-inline-flex"><strong>Total:&nbsp;</strong> <p class="product-price" data-price="{{ order.total }}">{{ order.total }}</p></li>
                    </ul>
                </div>
        
                <!-- Columna 2: Información del Cliente -->
                <div class="col-12 col-md-6">
                    <h3>Información del Cliente</h3>
                    <ul class="list-unstyled">
                        <li><strong>Teléfono:</strong> {{ order.user.phone_number }}</li>
                        <li><strong>Comuna:</strong> {{ order.user.comuna }}</li>
                        <li><strong>Correo:</strong> {{ order.user.email }}</li>
                        <li><strong>Género:</strong> {{ order.user.get_gender_display}}</li>
                        <li><strong>Edad:</strong> {{ age }}</li>
                </div>
            </div>

            <h4>Productos</h4>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Producto</th>
                        <th>Imagen</th>
                        <th>Cantidad</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in detalles %}
                    <tr>
                        <td>{{ p.product }}</td>
                        <td>
                            {% if p.product.image %}
                            <img class="img-fluid myimg-order" src="{{ p.product.image.url }}" alt="">
                            {% else %}
                            <img class="img-fluid myimg-order" src="{% static 'crud/img/image_not_found.jpg' %}" alt="">
                            {% endif %}
                        </td>
                        <td>{{ p.quantity }}</td>
                        <td class="product-price" data-price="{{ p.subtotal }}"">{{ p.subtotal }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <a class="btn btn-light" href="{% url 'order-list' %}">Volver</a>
        </div>
    </div>
</div>
{% endblock %}

{% block my_js %}
<script src="{% static 'crud/js/funciones.js' %}"></script>
{% endblock %}

crud/templates/crud/order-list.html
{% extends 'crud/base.html' %}
{% block title %}Pedidos{% endblock %}

{% load static %}
{% block meta_extra %}
    <meta name="csrf-token" content="{{ csrf_token }}">
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'crud/css/product-list.css' %}">
{% endblock %}

{% block first_content %}

<div class="mycontainer">
    {% if messages %}
    <div class="alert {{ request.session.level_mensaje }} alert-dismissible" role="alert">
        <ul>
            {% for message in messages %}
            <li><strong>{{message}}</strong></li>
            {% endfor %}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </ul>
    </div>

    {% endif %}
    <div class="container-fluid order-panel px-auto">
        <div class="row m-0">
            <div id="myFilters" class="col">
                <!-- FILTROS -->
                <div id="filters" class="p-4">
                    <h3 class="filter-title">Filtros</h3>

                    <form method="get" action="{% url 'order-list' %}">
                        <div class="form-group">
                            <label for="estado-filter" class="form-label mt-2">Filtrar por Estado:</label>
                            <select id="estado-filter" name="estado" class="form-control">
                                <option value="">Todos</option>
                                {% for key, value in estado_choices %}
                                    <option value="{{ key }}" {% if key == estado_seleccionado %}selected{% endif %}>{{ value }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="apply-filters mt-3">
                            <button type="submit" id="apply-filters-btn" class="product-btn">Aplicar filtros</button>
                        </div>
                    </form>
                </div>


            </div>
            <div class="col-lg-10 p-0">
                <h3 class="filter-title my-4">Pedidos</h3>
                <div class="py-3 my-4 container-fluid mx-auto">

                    <div class="table-responsive">
                        <table class="table myTable table-hover">
                            <thead class="table-head">
                                <tr>
                                    <th>ID Pedido</th>
                                    <th>Nombre Cliente</th>
                                    <th>Estado</th>
                                    <th>Total</th>
                                    <th class="text-center">Acciones</th>
                                </tr>
                            </thead>
                            <tbody class="table-body">
                                {% for s in pedidos %}
                                <tr data-order-id="{{s.id}}">
                                    <td class="order-id">
                                        <h6><a class="card-link text-decoration-none" href="">{{s.id}}</a></h6>
                                    </td>
                                    <td>
                                        <h6>{{ s.user.name }} {{ s.user.last_name }}</h6>
                                    </td>
                                    <td  class="order-status">
                                        <h6>
                                            <a class="card-link text-decoration-none" href="">
                                                {{ s.get_status_display }}</a>
                                        </h6>
                                    </td>
                                    <td>
                                        <p class="product-price" data-price="{{ s.total }}">{{ s.total }}</p>
                                    </td>
                                    <td class="tbActions">
                                        <div class="myActions container">
                                            <div class="row row-cols-3  text-center pt-2">
                                                <div class="col-3 me-4">
                                                    <a class="btn detalle-btn"
                                                        href="{% url 'order-detail' id=s.id %}">Detalle</a>
                                                </div>
                                                <div class="col-3 ms-3">
                                                    <button class="btn btn-outline-none btn-circle btn-confirm"
                                                        data-order-id="{{ s.id }}">
                                                        <span class="fs-5">
                                                            <i class="fa-solid fa-check"></i>
                                                        </span>
                                                    </button>
                                                </div>
                                                <div class="col-3">
                                                    <button class="btn btn-outline-none btn-circle btn-cancel"
                                                        data-order-id="{{ s.id }}">
                                                        <span class="fs-5">
                                                            <i class="fa-solid fa-xmark"></i>
                                                        </span>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


{% endblock %}

{% block my_js %}
<script src="{% static 'crud/js/funciones.js' %}"></script>

{% endblock %}